name: Deploy Spring Boot App to AWS EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: Build and tag Docker image
        run: docker build -t ${{ secrets.ECR_REGISTRY }}:${{ github.sha }} .

      - name: Configure AWS Credentials (for ECR push)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-ids: ${{ secrets.AWS_ACCOUNT_ID }}
          aws-region: us-east-1

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_REGISTRY }}:${{ github.sha }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run tests and check Jacoco coverage
        run: |
          mvn clean verify
          COVERAGE=$(mvn jacoco:report | grep "overall:" | awk '{print $2}' | tr -d "%,")
          echo "Code coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 60" | bc -l) )); then
            echo "Code coverage is below 60%. Failing the build."
            exit 1
          fi

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Conf
